# Generated by Django 5.2 on 2025-05-05 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение/иконка')),
                ('advantages', models.TextField(blank=True, verbose_name='Преимущества (по одному на строку)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_examples/', verbose_name='Фото примера работы')),
                ('video', models.FileField(blank=True, null=True, upload_to='service_examples/videos/', verbose_name='Видео примера работы')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='services.service', verbose_name='Услуга')),
            ],
        ),
    ]
