# Generated by Django 5.2 on 2025-05-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_photos/', verbose_name='Фото примера работы')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Фото услуги',
                'verbose_name_plural': 'Фото услуг',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='service_videos/', verbose_name='Видео примера работы')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Видео услуги',
                'verbose_name_plural': 'Видео услуг',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceExample',
        ),
    ]
