# Generated by Django 5.2 on 2025-05-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicephoto_servicevideo_delete_serviceexample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
