# Generated by Django 5.2 on 2026-04-24 13:23

import django.core.validators
import stroyma.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение/иконка'),
        ),
        migrations.AlterField(
            model_name='servicephoto',
            name='image',
            field=models.ImageField(upload_to='service_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Фото примера работы'),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='video',
            field=models.FileField(upload_to='service_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), stroyma.validators.MaxFileSizeValidator(52428800, message='Максимальный размер видео — 50 МБ.')], verbose_name='Видео примера работы'),
        ),
    ]
