# Generated by Django 5.2 on 2025-05-13 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
    ]
