# Generated by Django 5.2 on 2026-04-24 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания токена'),
        ),
    ]
