# Generated by Django 5.2 on 2026-09-30 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_confirmation_token_created_at'),
        ('products', '0020_product_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Согласие: личный кабинет'), ('contact', 'Согласие: обратная связь'), ('color_selection', 'Согласие: подбор цвета'), ('sale', 'Принятие условий продажи')], max_length=32, verbose_name='Документ')),
                ('version', models.CharField(max_length=32, verbose_name='Редакция')),
                ('document_snapshot', models.TextField(verbose_name='Сохранённый текст документа')),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата подтверждения')),
                ('source_path', models.CharField(max_length=255, verbose_name='Адрес формы')),
                ('subject', models.CharField(max_length=254, verbose_name='Email или телефон заявителя')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_acceptance', to='products.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение документа',
                'verbose_name_plural': 'Подтверждения документов',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
