"""
Django settings for stroyma project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Улучшенный интерфейс админки
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',  # Добавляем для поддержки sitemap
    'mptt',  # Добавлено для поддержки иерархических категорий
    'django_filters',  # Добавлено для фильтрации
    'rangefilter',  # Добавлено для фильтрации по диапазону дат
    'import_export',  # Добавлено для экспорта данных
    'accounts',
    'products',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Добавлен для поддержки локализации
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stroyma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Добавлен для поддержки переводов в шаблонах
            ],
        },
    },
]

WSGI_APPLICATION = 'stroyma.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'  # Изменено с 'en-us' на 'ru-ru' для русского языка по умолчанию

# Список доступных языков (можно расширить в будущем)
LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
]

# Путь для хранения файлов переводов
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True  # Включено для поддержки интернационализации
USE_L10N = True  # Включено для локализованных форматов (даты, числа и т.д.)
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для MEDIA (изображений)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# Настройки Jazzmin (для улучшения интерфейса админ-панели)
JAZZMIN_SETTINGS = {
    "site_title": "Stroyma",
    "site_header": "Stroyma",
    "site_brand": "STROYMA",
    "site_logo": None,
    "welcome_sign": "Добро пожаловать в панель управления Stroyma",
    "copyright": "Stroyma ООО",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,

    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,

    "hide_apps": ["auth"],
    "hide_models": [
        "products.BaseTexture",
        "products.FacadeColor",
    ],

    "order_with_respect_to": ["products", "services", "accounts"],

    "custom_links": {
        "products": [
            {
                "name": "Отчет по продажам",
                "url": "admin:sales_report",
                "icon": "fas fa-chart-line",
                "permissions": ["products.view_order"],
            }
        ],
    },

    "topmenu_links": [
        {"name": "Главная сайта", "url": "/", "new_window": True},
        {"name": "Отчёт", "url": "admin:sales_report"},
    ],

    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "products.Product": "fas fa-box-open",
        "products.Category": "fas fa-sitemap",
        "products.Order": "fas fa-file-invoice-dollar",
        "products.FacadeColor": "fas fa-palette",
        "products.BaseTexture": "fas fa-brush",
        "services.Service": "fas fa-hard-hat",
        "services.ServicePhoto": "fas fa-images",
        "services.ServiceVideo": "fas fa-video",
        "accounts.UserProfile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },

    "language_chooser": False,
    "custom_css": "css/admin_custom.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# Настройки для кеширования
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 300,  # Максимальное количество объектов в кеше
            'CULL_FREQUENCY': 3,  # Частота очистки кеша при превышении лимита 
        }
    }
}

# Настройки API агрегации данных для кеша
DATA_CACHE_TIMEOUT = 60 * 30  # 30 минут для данных отчетов
PRODUCT_CACHE_TIMEOUT = 60 * 60  # 1 час для данных о товарах
POPULAR_PRODUCTS_TIMEOUT = 60 * 60 * 3  # 3 часа для популярных товаров
