"""
Django settings for stroyma project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from csp.constants import NONE, SELF, UNSAFE_EVAL, UNSAFE_INLINE
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# URL админки (без ведущего слеша, со слешем в конце), например "admin/" или "secret-path/"
ADMIN_URL = config('ADMIN_URL', default='admin/').strip()
if not ADMIN_URL:
    ADMIN_URL = 'admin/'
if not ADMIN_URL.endswith('/'):
    ADMIN_URL = ADMIN_URL + '/'

LOGS_DIR = BASE_DIR / 'logs'
try:
    LOGS_DIR.mkdir(exist_ok=True)
except OSError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# Старые ключи при ротации SECRET_KEY (через запятую в .env, без пробелов)
SECRET_KEY_FALLBACKS = [k for k in config('SECRET_KEY_FALLBACKS', default='', cast=Csv()) if k]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'jazzmin',  # Улучшенный интерфейс админки
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',  # Добавляем для поддержки sitemap
    'axes',
    'csp',
    'mptt',  # Добавлено для поддержки иерархических категорий
    'django_filters',  # Добавлено для фильтрации
    'rangefilter',  # Добавлено для фильтрации по диапазону дат
    'import_export',  # Добавлено для экспорта данных
    'colorfield',  # Добавлено для цветовых полей в админке
    'accounts',
    'products',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # После CommonMiddleware (рекомендация Django)
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'stroyma.urls'

# Аутентификация: django-axes (брутфорс) + стандартный backend
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Добавлен для поддержки переводов в шаблонах
                'products.context_processors.cart_info',  # Глобальный счётчик корзины
            ],
        },
    },
]

WSGI_APPLICATION = 'stroyma.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'  # Изменено с 'en-us' на 'ru-ru' для русского языка по умолчанию

# Список доступных языков (можно расширить в будущем)
LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
]

# Путь для хранения файлов переводов
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True  # Включено для поддержки интернационализации
USE_L10N = True  # Включено для локализованных форматов (даты, числа и т.д.)
USE_TZ = True

# Сессия и CSRF
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False

# Лимиты размера запроса (видео в админке — до 50 МБ, см. stroyma.validators)
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для MEDIA (изображений)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
# Сек: не крутить весь HTTP-запрос, если SMTP недоступен (локальная разработка, файрвол)
EMAIL_TIMEOUT = int(config('EMAIL_TIMEOUT', default='20'))
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# Куда слать уведомления о новых заказах и заявках (пусто = EMAIL_HOST_USER)
ORDER_NOTIFY_EMAIL = (config('ORDER_NOTIFY_EMAIL', default='') or '').strip() or EMAIL_HOST_USER

# Настройки Jazzmin (для улучшения интерфейса админ-панели)
JAZZMIN_SETTINGS = {
    "site_title": "Stroyma",
    "site_header": "Stroyma",
    "site_brand": "STROYMA",
    "site_logo": None,
    "welcome_sign": "Добро пожаловать в панель управления Stroyma",
    "copyright": "Stroyma ООО",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,

    "show_ui_builder": False,
    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,

    "hide_apps": ["auth"],
    "hide_models": [
        "products.BaseTexture",
        "products.FacadeColor",
    ],

    "order_with_respect_to": ["products", "services", "accounts"],

    "custom_links": {
        "products": [
            {
                "name": "Отчет по продажам",
                "url": "admin:sales_report",
                "icon": "fas fa-chart-line",
                "permissions": ["products.view_order"],
            }
        ],
    },

    "topmenu_links": [
        {"name": "Главная сайта", "url": "/", "new_window": True},
        {"name": "Отчёт", "url": "admin:sales_report"},
    ],

    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        "products.Product": "fas fa-box-open",
        "products.Category": "fas fa-sitemap",
        "products.Order": "fas fa-file-invoice-dollar",
        "products.FacadeColor": "fas fa-palette",
        "products.BaseTexture": "fas fa-brush",
        "services.Service": "fas fa-hard-hat",
        "services.ServicePhoto": "fas fa-images",
        "services.ServiceVideo": "fas fa-video",
        "accounts.UserProfile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },

    "language_chooser": False,
    "custom_css": "css/admin_custom.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# Продакшен-безопасность: включаем только если DEBUG=False
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=60 * 60 * 24 * 30, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Локальная разработка: cookie без secure
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Content-Security-Policy (публичный фронт: Tailwind CDN, Google Fonts, cdnjs)
_csp_admin_prefix = '/' + ADMIN_URL.rstrip('/').lstrip('/') + '/'
CONTENT_SECURITY_POLICY = {
    'EXCLUDE_URL_PREFIXES': [_csp_admin_prefix],
    'DIRECTIVES': {
        'default-src': [SELF],
        'script-src': [SELF, 'https://cdn.tailwindcss.com', UNSAFE_INLINE, UNSAFE_EVAL],
        'style-src': [
            SELF,
            UNSAFE_INLINE,
            'https://fonts.googleapis.com',
            'https://cdnjs.cloudflare.com',
        ],
        'font-src': [SELF, 'https://fonts.gstatic.com', 'https://cdnjs.cloudflare.com'],
        'img-src': [SELF, 'data:', 'https:'],
        'connect-src': [SELF],
        # Виджеты Яндекс.Карт (iframe на contact.html и др.); без frame-src падает в default-src 'self'
        'frame-src': [
            SELF,
            'https://yandex.ru',
            'https://yandex.com',
        ],
        'frame-ancestors': [NONE],
        'form-action': [SELF],
        'base-uri': [SELF],
    },
}

# django-axes: блокировка после N неудачных попыток входа
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=5, cast=int)
AXES_COOLOFF_TIME = timedelta(hours=config('AXES_COOLOFF_HOURS', default=1, cast=int))
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]

# django-ratelimit использует default cache
RATELIMIT_USE_CACHE = 'default'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'app_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'app.log'),
            'maxBytes': 2 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 2 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
        },
        'django.security': {
            'handlers': ['app_file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Настройки для кеширования
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 300,  # Максимальное количество объектов в кеше
            'CULL_FREQUENCY': 3,  # Частота очистки кеша при превышении лимита
        }
    }
}

# Опциональный Redis-кеш: задайте REDIS_URL в .env, чтобы включить
REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'TIMEOUT': 300,
    }

# Настройки API агрегации данных для кеша
DATA_CACHE_TIMEOUT = 60 * 30  # 30 минут для данных отчетов
PRODUCT_CACHE_TIMEOUT = 60 * 60  # 1 час для данных о товарах
POPULAR_PRODUCTS_TIMEOUT = 60 * 60 * 3  # 3 часа для популярных товаров
