# Generated by Django 5.2 on 2025-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название текстуры')),
                ('image', models.ImageField(upload_to='base_textures/', verbose_name='Изображение текстуры')),
            ],
        ),
        migrations.CreateModel(
            name='FacadeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('hex_code', models.CharField(max_length=7, verbose_name='Код цвета (HEX)')),
            ],
        ),
    ]
