# Generated by Django 5.2 on 2026-04-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_created_at_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('processing', 'Обработка'), ('shipped', 'Доставляется'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('processing', 'Обработка'), ('shipped', 'Доставляется'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='products.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Контакты заказа',
                'verbose_name_plural': 'Контакты заказов',
            },
        ),
    ]
