# Generated by Django 5.2 on 2026-04-24 13:23

import django.core.validators
import stroyma.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_data_canceled_to_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetexture',
            name='image',
            field=models.ImageField(upload_to='base_textures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение текстуры'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
    ]
