# Generated by Django 5.2 on 2026-09-29 15:41

import django.core.validators
import stroyma.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ товара в исходной выгрузке'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), stroyma.validators.MaxFileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='0 — цена уточняется, заказ через корзину недоступен', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Остаток на складе'),
        ),
    ]
