# Generated by Django 5.2 on 2026-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_info',
            field=models.TextField(blank=True, help_text='Сведения из маркировки или документации изготовителя; не подставляйте адрес продавца.', verbose_name='Изготовитель и его адрес'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место изготовления'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_info',
            field=models.TextField(blank=True, help_text='Основные правила безопасного применения и хранения, сведения об обязательном подтверждении соответствия, если применимо.', verbose_name='Применение, хранение и безопасность'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.TextField(blank=True, help_text='Укажите установленные изготовителем сроки и условия. Если конкретный срок не установлен, укажите это по документации.', verbose_name='Гарантия, срок службы и срок годности'),
        ),
    ]
