# Generated by Django 5.2 on 2026-09-30 12:21

from django.db import migrations, models


def backfill_units(apps, schema_editor):
    OrderItem = apps.get_model('products', 'OrderItem')
    Product = apps.get_model('products', 'Product')
    database = schema_editor.connection.alias
    for product in Product.objects.using(database).only('pk', 'unit').iterator():
        OrderItem.objects.using(database).filter(product_id=product.pk).update(product_unit=product.unit)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_manufacturer_info_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Единица на момент заказа'),
        ),
        migrations.RunPython(backfill_units, migrations.RunPython.noop),
    ]
